#!/usr/bin/perl

use strict;
use warnings;
use 5.010;

use FindBin;
use lib "$FindBin::Bin/../Kinza/lib";
use Kinza::Schema;

my $sch = Kinza::Schema->get_schema;

my $course_rs = $sch->resultset('Course');

$sch->txn_do( sub {
  while (my $course = $course_rs->next) {
    if ($course->number_of_terms == 5) {
      my $term = $sch->resultset('Term')->find({
        seq => 1,
      });
      $course->add_to_presentations({
        term_id => $term->id,
      });
    } else {
      foreach my $term ($sch->resultset('Term')->all) {
        $course->add_to_presentations({
          term_id => $term->id,
        });
      }
    }
  }
});
