#!/usr/bin/perl

use strict;
use warnings;
use 5.010;

use FindBin '$Bin';
use lib "$Bin/../Kinza/lib";
use Kinza::Schema;

my $sch = Kinza::Schema->get_schema;
my $st_rs = $sch->resultset('Student');

my ($looked, $found);
while (<>) {
  chomp;
  my ($name, $email) = (split /\s*,\s*/)[0, 2];

  my $st = $st_rs->find({
    name => $name,
  });

  $looked++;
  unless ($st) {
    say "Can't find $name";
    next;
  }

  $found++;
  say "Found $name";
  $st->update({ email => $email });
}

say "Looked for $looked. Found $found";
